/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anyonavinfo_bluetoothphone_imxserial_SerialPort */

#ifndef _Included_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort
#define _Included_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anyonavinfo_bluetoothphone_imxserial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_anyonavinfo_bluetoothphone_imxserial_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort_close
        (JNIEnv *, jobject);

/*
 * Class:     com_anyonavinfo_bluetoothphone_bpservice_imxserial_VolumeChannel
 * Method:    getVolumeChannelState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort_getVolumeChannelState
        (JNIEnv *, jclass);

/*
 * Class:     com_anyonavinfo_bluetoothphone_bpservice_imxserial_VolumeChannel
 * Method:    setVolumeChannelState
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_anyonavinfo_bluetoothphone_bpservice_imxserial_SerialPort_setVolumeChannelState
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
